package org.ttt.autogenesis.server

import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.delay
import kotlinx.coroutines.isActive
import kotlinx.coroutines.launch
import org.ttt.autogenesis.logging.LogCategory
import org.ttt.autogenesis.logging.Logger
import org.ttt.autogenesis.network.RpcMessage.AgentWorkStreamData

/**
 * Coordinates buffering and delivery of pipeline streaming data for each connected player.
 *
 * Each connection gets a small StringBuilder buffer that flushes every ${FLUSH_INTERVAL_MS}ms,
 * so that heavy streaming output (via [streamPipelineOutputToAgentWorkBuffer]) does not overwhelm a
 * single WebSocket send. When pipelines complete we flush with `isComplete=true` so the client can
 * finalize the window.
 */
internal object AgentWorkStreamDispatcher
{
    private const val STREAM_ID = "agent-work"
    private const val FLUSH_INTERVAL_MS = 250L

    private val scope = CoroutineScope(SupervisorJob() + Dispatchers.Default)
    private val lock = Any()
    private val connectionStates = mutableMapOf<String, ConnectionState>()

    private data class ConnectionState(
        val buffer: StringBuilder = StringBuilder(),
        var streaming: Boolean = false,
        var flushJob: Job? = null
    )

    /**
     * Begins aggregating chunks for the given connection and schedules periodic flushes.
     */
    fun subscribe(connectionId: String)
    {
        synchronized(lock)
        {
            val state = connectionStates.getOrPut(connectionId) { ConnectionState() }
            if(state.streaming) return
            state.streaming = true
            startFlushJob(connectionId, state)
        }
        Logger.debug(LogCategory.NETWORK, "AgentWorkStreamDispatcher: Subscribed $connectionId")
    }

    /**
     * Stops buffering for the connection, flushes any remaining text with a completion flag, and
     * releases state to avoid leaking memory.
     */
    fun unsubscribe(connectionId: String)
    {
        val state = synchronized(lock)
        {
            val candidate = connectionStates[connectionId] ?: return
            candidate.streaming = false
            candidate.flushJob?.cancel()
            candidate.flushJob = null
            candidate
        }
        flushBuffer(connectionId, isComplete = true)
        synchronized(lock)
        {
            connectionStates.remove(connectionId)
        }
        Logger.debug(LogCategory.NETWORK, "AgentWorkStreamDispatcher: Unsubscribed $connectionId")
    }

    /**
     * Appends the next chunk generated by a streaming [Pipe]. The chunk is dropped if the
     * subscription no longer exists or is currently paused.
     */
    /**
     * Appends a chunk to the buffer for a specific connection if it's subscribed.
     * Silently ignores unsubscribed connections to allow dynamic subscription.
     */
    fun appendChunk(connectionId: String, chunk: String)
    {
        if(chunk.isEmpty()) return
        synchronized(lock)
        {
            val state = connectionStates[connectionId]
            if(state == null || !state.streaming)
            {
                // Client not subscribed yet - silently ignore
                return
            }
            state.buffer.append(chunk)
        }
    }

    /**
     * Appends one chunk to all currently subscribed recipients in [connectionIds].
     */
    fun appendChunkToMany(connectionIds: Collection<String>, chunk: String)
    {
        if(chunk.isEmpty()) return
        connectionIds.forEach { connectionId ->
            appendChunk(connectionId, chunk)
        }
    }

    /**
     * Notifies the dispatcher that an entire pipeline finished so the client can render
     * `isComplete=true` and stop showing the spinner.
     */
    fun notifyPipelineComplete(connectionId: String)
    {
        flushBuffer(connectionId, isComplete = true)
    }

    /**
     * Marks all provided recipients complete for the active pipeline.
     */
    fun notifyPipelineCompleteMany(connectionIds: Collection<String>)
    {
        Logger.debug(LogCategory.NETWORK, "AgentWorkStreamDispatcher: Completing stream for ${connectionIds.size} recipients")
        connectionIds.forEach { connectionId ->
            notifyPipelineComplete(connectionId)
        }
    }

    /**
     * Returns true when [connectionId] currently has an active agent-work subscription.
     */
    fun isSubscribed(connectionId: String): Boolean
    {
        return synchronized(lock)
        {
            connectionStates[connectionId]?.streaming == true
        }
    }

    private fun startFlushJob(connectionId: String, state: ConnectionState)
    {
        if(state.flushJob != null) return
        state.flushJob = scope.launch {
            while(isActive)
            {
                delay(FLUSH_INTERVAL_MS)
                flushBuffer(connectionId, isComplete = false)
            }
        }
    }

    private fun flushBuffer(connectionId: String, isComplete: Boolean)
    {
        val chunk = synchronized(lock)
        {
            val state = connectionStates[connectionId] ?: return
            val pending = state.buffer.toString()
            if(pending.isEmpty() && !isComplete) return
            state.buffer.clear()
            pending
        }

        val payload = AgentWorkStreamData(
            connectionId = connectionId,
            streamId = STREAM_ID,
            content = chunk,
            isComplete = isComplete
        )
        scope.launch {
            try
            {
                UiSignalRpcHandlers.sendAgentWorkStream(connectionId, payload)
            }
            catch(err: Throwable)
            {
                Logger.warn(LogCategory.NETWORK, "AgentWorkStreamDispatcher: Failed to deliver stream chunk for $connectionId: ${err.message}")
            }
        }
    }
}