plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.kvision)
    alias(libs.plugins.ksp)
}

import java.util.Base64

// Build-time toggle for the client-side `globals.ClientDebug.debugMode` flag,
// which selects between local server URLs and live AGS URLs. Materialized as
// a generated source file (`LiveMode.kt`) under `build/generated/liveMode/`
// and added to the `jsMain` source set. Read in
// `kvisionApp/src/jsMain/kotlin/globals/Debug.kt` via the generated
// `globals.LiveMode` object. Default is `false` (local / debug mode) so
// existing dev builds keep working.
val kvisionLiveMode: Boolean = (project.findProperty("kvision.liveMode") as String?)
    ?.toBooleanStrictOrNull()
    ?: false

kotlin {
    js(IR) {
        browser {
            commonWebpackConfig {
                cssSupport {
                    enabled.set(true)
                }
            }
        }
        binaries.executable()
    }

    sourceSets {
        val commonMain by getting
        val jsMain by getting {
            dependencies {
                implementation(project(":accelbyteSdk"))
                implementation(project(":sharedModel"))
                implementation(libs.kvision)
                implementation(libs.kvisionJs)
                implementation(libs.kvisionBootstrap)
                implementation(libs.kotlinx.coroutines.core)
                implementation("io.kvision:kvision-fontawesome:9.1.1")
                implementation(npm("@connectrpc/connect", "1.7.0"))
                implementation(npm("@connectrpc/connect-web", "1.7.0"))
                implementation(npm("@bufbuild/protobuf", "1.10.1"))
                implementation(npm("marked", "4.3.0"))
                implementation(npm("process", "0.11.10"))
            }
            kotlin.srcDir(buildDir.resolve("generated/ksp/js/jsMain/kotlin"))
        }
        val commonTest by getting
        val jsTest by getting {
            dependencies {
                implementation(kotlin("test-js"))
                implementation(libs.kotlinx.coroutines.test)
            }
        }
    }
}

// Generate `LiveMode.kt` from the `kvision.liveMode` Gradle property. Putting
// the value in a real Kotlin file (rather than a `-Xdefine=...` free compiler
// arg) is portable across Kotlin/JS compiler versions and is visible to the
// IDE / ktlint / ksp.
val liveModeGeneratedDir: java.io.File = layout.buildDirectory.dir("generated/liveMode").get().asFile
val generateLiveMode by tasks.registering {
    group = "build"
    description = "Generates LiveMode.kt from the kvision.liveMode Gradle property."
    outputs.dir(liveModeGeneratedDir)
    inputs.property("kvisionLiveMode", kvisionLiveMode)
    doLast {
        liveModeGeneratedDir.mkdirs()
        val file = File(liveModeGeneratedDir, "LiveMode.kt")
        file.writeText(
            """// Auto-generated by kvisionApp/build.gradle.kts — do not edit by hand.
package globals

/** Build-time mirror of the kvisionApp `kvision.liveMode` Gradle property. */
object LiveMode {
    const val liveMode: Boolean = ${kvisionLiveMode}
}
"""
        )
    }
}

kotlin.sourceSets.named("jsMain") {
    kotlin.srcDir(liveModeGeneratedDir)
}

tasks.matching { it.name.startsWith("compileKotlinJs") || it.name.startsWith("kspKotlinJs") }
    .configureEach { dependsOn(generateLiveMode); dependsOn(generateVapidKeys) }

// Generate a VAPID P-256 ECDSA keypair for Web Push notifications.
// The private key is written to ~/.autogenesis/vapid_private.pem (created on
// first run, never regenerated thereafter). The public key is extracted and
// Base64URL-encoded into build/generated/vapid/vapid_public.json so the
// Kotlin/JS PushNotificationService can fetch it as the
// `applicationServerKey` argument to `pushManager.subscribe()`.
val vapidDir: java.io.File = layout.buildDirectory.dir("generated/vapid").get().asFile
val generateVapidKeys by tasks.registering {
    group = "build"
    description = "Generates VAPID P-256 ECDSA keypair at ~/.autogenesis/vapid_private.pem and writes the Base64URL-encoded public key into build/generated/vapid/vapid_public.json."
    outputs.dir(vapidDir)
    doLast {
        vapidDir.mkdirs()
        val homeDir = System.getProperty("user.home") ?: System.getenv("HOME") ?: "/root"
        val privateKeyFile = File(File(homeDir, ".autogenesis"), "vapid_private.pem")
        if (!privateKeyFile.exists()) {
            privateKeyFile.parentFile.mkdirs()
            val genProcess = ProcessBuilder(
                "openssl", "ecparam", "-name", "prime256v1", "-genkey", "-noout",
                "-out", privateKeyFile.absolutePath
            ).redirectErrorStream(true).start()
            val genExit = genProcess.waitFor()
            val genOutput = genProcess.inputStream.bufferedReader().readText()
            check(genExit == 0) { "openssl ecparam failed (exit=$genExit): $genOutput" }
            logger.warn("Generated VAPID private key at ${privateKeyFile.absolutePath}")
        }
        // Extract the public key as DER (SubjectPublicKeyInfo, X.509), then
        // strip the SEQUENCE/OID headers and BIT STRING tag+length to get the
        // raw 65-byte uncompressed point (0x04 || X || Y), then Base64URL-encode
        // it (no padding) for the applicationServerKey parameter.
        val derProcess = ProcessBuilder(
            "openssl", "ec", "-in", privateKeyFile.absolutePath, "-pubout",
            "-outform", "DER"
        ).redirectErrorStream(true).start()
        val derBytes = derProcess.inputStream.readBytes()
        val derExit = derProcess.waitFor()
        val derOutput = String(derBytes)
        check(derExit == 0) { "openssl ec -pubout failed: $derOutput" }
        val rawPoint = derBytes.copyOfRange(derBytes.size - 65, derBytes.size)
        val encoder = Base64.getUrlEncoder().withoutPadding()
        val base64Url = encoder.encodeToString(rawPoint)
        val outFile = File(vapidDir, "vapid_public.json")
        outFile.writeText("""{"applicationServerKey":"$base64Url"}""")
        logger.lifecycle("VAPID public key written to ${outFile.absolutePath} (${base64Url.length} chars)")
    }
}

dependencies {
    add("kspJs", project(":rpc-ksp"))
}

// Ensure KSP regenerates for new @RpcMethod annotations in client
afterEvaluate {
    tasks.findByName("kspKotlinJs")?.let { kspTask ->
        tasks.findByName("compileKotlinJs")?.let { compileTask ->
            compileTask.dependsOn(kspTask)
        }
        // Force KSP to always run to catch new annotations
        kspTask.outputs.upToDateWhen { false }
    }
}

val grpcBridgeProtoDir = rootProject.file("grpcBridgeProto")
val grpcResourcesDir = projectDir.resolve("src/jsMain/resources/grpc")

val installGrpcProtoPlugins by tasks.registering(Exec::class) {
    group = "build"
    description = "Installs the npm plugins for grpc-web generation."
    workingDir = grpcBridgeProtoDir
    commandLine("npm", "install")
    inputs.file(grpcBridgeProtoDir.resolve("package.json"))
    outputs.dir(grpcBridgeProtoDir.resolve("node_modules"))
}

val protocBinProvider = providers.gradleProperty("grpcBridgeProtoc")
    .orElse(providers.environmentVariable("PROTOC_BIN"))
    .orElse("protoc")

val generateGrpcWeb by tasks.registering(Exec::class) {
    group = "build"
    description = "Regenerates the grpc-web JS stubs for the Kotlin/JS client."
    dependsOn(installGrpcProtoPlugins)
    workingDir = rootProject.projectDir
    commandLine("bash", rootProject.file("scripts/generate-grpc-web.sh").absolutePath)
    environment("PROTOC_BIN", protocBinProvider.get())
    inputs.file(rootProject.file("scripts/generate-grpc-web.sh"))
    inputs.dir(grpcBridgeProtoDir.resolve("src/main/proto"))
    inputs.file(grpcBridgeProtoDir.resolve("package.json"))
    outputs.dir(grpcResourcesDir)
}

tasks.named("jsProcessResources") {
    dependsOn(generateGrpcWeb)
}

// The Kotlin/JS multiplatform plugin only copies resources from the
// declaring module's own source sets into jsProcessResources output;
// resources declared on a *dependency* module (e.g. the sharedModel
// commonMain resources) are NOT merged into the consuming module's
// processedResources tree. `MenuMusicPlayer` fetches
// `audio/audio-tracks.json` from the dev server's public path, which
// is rooted at `kvisionApp/build/processedResources/js/main`, so we
// have to physically copy the JSON in via a small sync task. The file
// itself is the designer's authoritative catalog (server's
// `MusicSelector` reads the same file via classpath), so the source
// of truth is the sharedModel module — this task mirrors it into the
// kvisionApp's processed resources before they are served.
val syncSharedAudioTracks by tasks.registering(Copy::class) {
    group = "build"
    description = "Copies sharedModel's commonMain audio-tracks.json into kvisionApp's processedResources/js/main/audio/."
    from(rootProject.file("sharedModel/src/commonMain/resources/audio/audio-tracks.json"))
    into(layout.buildDirectory.dir("processedResources/js/main/audio"))
    inputs.file(rootProject.file("sharedModel/src/commonMain/resources/audio/audio-tracks.json"))
    outputs.file(layout.buildDirectory.file("processedResources/js/main/audio/audio-tracks.json"))
}

tasks.named("jsProcessResources") {
    dependsOn(syncSharedAudioTracks)
}

// Copy `kvision-iam.local.properties` and `kvision-global.local.properties` from the
// module root into the JS processed resources directory so ConfigSource.property() can
// fetch them via sync XHR at app startup. Source files are written by the
// `autogenesis-secrets/scripts/sync-resources.sh` script and are .gitignored. If
// they are absent, the copy is skipped — ConfigSource will surface a clear error
// at first access.
val localPropertiesJsDir = layout.buildDirectory.dir("processedResources/js/main").get().asFile

val copyKvisionIamLocalProperties by tasks.registering(Copy::class) {
    group = "build"
    description = "Copies kvision-iam.local.properties into the JS processed resources."
    from(layout.projectDirectory.file("kvision-iam.local.properties"))
    into(localPropertiesJsDir)
    inputs.file(layout.projectDirectory.file("kvision-iam.local.properties"))
    outputs.file(layout.buildDirectory.file("processedResources/js/main/kvision-iam.local.properties"))
}

val copyKvisionGlobalLocalProperties by tasks.registering(Copy::class) {
    group = "build"
    description = "Copies kvision-global.local.properties into the JS processed resources."
    from(layout.projectDirectory.file("kvision-global.local.properties"))
    into(localPropertiesJsDir)
    inputs.file(layout.projectDirectory.file("kvision-global.local.properties"))
    outputs.file(layout.buildDirectory.file("processedResources/js/main/kvision-global.local.properties"))
}

tasks.named("jsProcessResources") {
    dependsOn(copyKvisionIamLocalProperties, copyKvisionGlobalLocalProperties)
}

// Forward `-PkvisionApp.bootWidget=<value>` Gradle property to the webpack
// DefinePlugin via the `AUTOGENESIS_BOOT_WIDGET` shell env var. The webpack
// config file `webpack.config.d/boot-widget-env.js` reads this var at bundle
// time and substitutes `process.env.AUTOGENESIS_BOOT_WIDGET` with the value.
//
// Default empty (no override) — production builds always boot MainMenu
// unless the operator explicitly opts in.
//
// Example:
//   ./gradlew runKvisionNoHotReload -PkvisionApp.bootWidget=MapViewer
//
// The webpack dev server task (`:kvisionApp:jsBrowserDevelopmentRun` /
// `runKvisionNoHotReload`) is a JavaExec; the production webpack bundle
// task is an Exec. Both extend ProcessForkOptions so `environment(...)`
// resolves.
//
// IMPORTANT: the kotlin-js plugin registers its webpack tasks during
// `kotlin { js { ... } }` evaluation, which runs at script-body time. The
// `runKvisionNoHotReload` task is registered separately in the root
// `build.gradle.kts`. Both kinds of tasks must be configured in
// `afterEvaluate { }` so the configuration block sees them — script-body
// configureEach only fires for tasks already in the collection, which is
// empty before plugin evaluation completes.
afterEvaluate {
    tasks.withType<JavaExec>().configureEach {
        if(name.contains("Webpack") || name.contains("Kvision") || name.contains("Browser")) {
            val bootWidgetValue: String = providers.gradleProperty("kvisionApp.bootWidget").orElse("").get()
            if(bootWidgetValue.isNotEmpty()) {
                environment("AUTOGENESIS_BOOT_WIDGET", bootWidgetValue)
            }
        }
    }
    tasks.withType<Exec>().configureEach {
        if(name.contains("Webpack") || name.contains("Kvision") || name.contains("Browser")) {
            val bootWidgetValue: String = providers.gradleProperty("kvisionApp.bootWidget").orElse("").get()
            if(bootWidgetValue.isNotEmpty()) {
                environment("AUTOGENESIS_BOOT_WIDGET", bootWidgetValue)
            }
        }
    }
    // Sibling block for AUTOGENESIS_DEMO_MODE (kvisionApp/demo-mode-env.js).
    // Same forwarder pattern. Valid values: off, widgets, full.
    tasks.withType<JavaExec>().configureEach {
        if(name.contains("Webpack") || name.contains("Kvision") || name.contains("Browser")) {
            val demoModeValue: String = providers.gradleProperty("kvisionApp.demoMode").orElse("").get()
            if(demoModeValue.isNotEmpty()) {
                environment("AUTOGENESIS_DEMO_MODE", demoModeValue)
            }
        }
    }
    tasks.withType<Exec>().configureEach {
        if(name.contains("Webpack") || name.contains("Kvision") || name.contains("Browser")) {
            val demoModeValue: String = providers.gradleProperty("kvisionApp.demoMode").orElse("").get()
            if(demoModeValue.isNotEmpty()) {
                environment("AUTOGENESIS_DEMO_MODE", demoModeValue)
            }
        }
    }
}
