package org.ttt.autogenesis.serverextend

import org.ttt.autogenesis.serverextend.config.AccelByteConfig
import org.ttt.autogenesis.config.ConfigSource
import matchmaking.MatchPoolBootstrap
import matchmaking.ServerConnector
import org.ttt.autogenesis.server.config.ServerConfig
import globals.AwsCredentialsBootstrap
import globals.ExtendConfig
import io.ktor.http.ContentType
import io.ktor.http.HttpHeaders
import io.ktor.http.HttpMethod
import io.ktor.http.HttpStatusCode
import io.ktor.server.application.Application
import io.ktor.server.application.ApplicationEnvironment
import io.ktor.server.application.call
import io.ktor.server.application.install
import io.ktor.server.engine.embeddedServer
import io.ktor.server.netty.Netty
import io.ktor.server.plugins.contentnegotiation.ContentNegotiation
import io.ktor.server.plugins.cors.routing.CORS
import io.ktor.server.request.receiveText
import io.ktor.server.response.respond
import io.ktor.server.response.respondTextWriter
import io.ktor.server.routing.get
import io.ktor.server.routing.post
import io.ktor.server.routing.routing
import io.ktor.serialization.kotlinx.json.json
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.collect
import kotlinx.coroutines.launch
import org.ttt.autogenesis.logging.LogCategory
import org.ttt.autogenesis.logging.LogPriority
import org.ttt.autogenesis.logging.Logger
import org.ttt.autogenesis.network.ConnectionStatus
import org.ttt.autogenesis.network.RpcCallContext
import org.ttt.autogenesis.network.RpcDirection
import org.ttt.autogenesis.network.RpcJson
import org.ttt.autogenesis.network.RpcMessage
import org.ttt.autogenesis.network.RpcOrigin
import org.ttt.autogenesis.network.RpcRegistry
import org.ttt.autogenesis.network.registerRpcSystem
import org.ttt.autogenesis.network.toJson
import org.ttt.autogenesis.network.toRpcMessage
import org.ttt.autogenesis.server.GrpcServer
import org.ttt.autogenesis.server.GrpcServerConfig
import org.ttt.autogenesis.server.vfs.VirtualFileSystemManager
import java.util.concurrent.CompletionException
import java.util.UUID

// Module-level RPC registry to ensure it's accessible to all handlers
private lateinit var moduleRpcRegistry: RpcRegistry
private var moduleGrpcServer: GrpcServer? = null

/**
 * Builds or returns the shared RPC registry used by both the REST and gRPC listeners.
 *
 * @return The initialized server-side RPC registry.
 */
internal fun ensureModuleRpcRegistry(): RpcRegistry
{
    if(!::moduleRpcRegistry.isInitialized)
    {
        registerRpcSystem()

        // Explicitly trigger server-extend specific RPC registrations to bypass classpath collisions with the main server.
        // These internal variables are generated by the @RpcMethod KSP processor.
        agent.runners._extendCommanderRunnerRpcHandlersProvider
        matchmaking._serverConnectorRpcHandlersProvider
        proxy._cloudSaveProxyRpcHandlersProvider

        moduleRpcRegistry = RpcRegistry(RpcDirection.SERVER)
    }

    return moduleRpcRegistry
}

/**
 * Main entry point for the REST-based server extension.
 * 
 * Initializes server configuration, virtual file system, and starts a Netty-based
 * HTTP server on port 7070 with REST endpoints for RPC communication and SSE streaming.
 * 
 * @param args Command line arguments passed to [ServerConfig]
 */
fun main(args: Array<String>)
{
    Logger.configure(LogPriority.DEBUG, true, maxLogFiles = 1, serverType = "server-extend")
    Logger.info(LogCategory.SYSTEM, "ServerExtend starting (args=${args.joinToString(",")})")

    // Initialize AccelByte configuration from file or environment
    AccelByteConfig

    AwsCredentialsBootstrap.initialize()

    // Initialize server configuration from command line arguments
    ServerConfig.args = args.toList()
    VirtualFileSystemManager.initialize(ServerConfig.args)

    // Phase 6 of feature/live-pvp-and-billing: install the BYO key provider
    // so the game server's BedrockCredentialResolver can swap to a player's
    // own AWS credentials during their turn. server-extend owns the
    // encrypted BYO slot; the resolver in :server consults this provider
    // via the static field to avoid a cyclic gradle dependency.
    globals.BedrockCredentialResolver.installByoKeyProvider(globals.ByoKeyProvider { userId ->
        account.ByoCredentialStore.getDecrypted(userId).getOrNull()?.let { slot ->
            globals.ByoKeyMaterial(
                accessKeyId = slot.keyId,
                secretAccessKey = slot.secret,
                region = slot.region
            )
        }
    })

    // Idempotently reconcile the matchmaking ladder pools against the AccelByte
    // match2 service. Skipped in dev mode so local Electron runs do not touch
    // the platform admin endpoints.
    if(!ExtendConfig.debugMode)
    {
        MatchPoolBootstrap.run()
    }
    else
    {
        Logger.info(LogCategory.SYSTEM, "ServerExtend: dev mode active — skipping MatchPoolBootstrap")
    }

    if(ExtendConfig.grpcEnabled)
    {
        GrpcServerConfig.host = ExtendConfig.grpcHost
        GrpcServerConfig.port = ExtendConfig.grpcPort
        Logger.info(
            LogCategory.SYSTEM,
            "ServerExtend: gRPC/grpc-web listener configured for ${GrpcServerConfig.host}:${GrpcServerConfig.port} " +
                "(override with -DserverExtend.grpcPort=<port> or SERVER_EXTEND_GRPC_PORT=<port>)"
        )
        try
        {
            moduleGrpcServer = GrpcServer(GrpcServerConfig, ensureModuleRpcRegistry()).apply {
                start()
            }
            Runtime.getRuntime().addShutdownHook(Thread {
                moduleGrpcServer?.stop()
            })
        }
        catch(e: CompletionException)
        {
            Logger.error(
                LogCategory.NETWORK,
                "ServerExtend: failed to bind gRPC/grpc-web listener on ${GrpcServerConfig.host}:${GrpcServerConfig.port}. " +
                    "Check whether another process is already using that port, or override it with " +
                    "-DserverExtend.grpcPort=<port> / SERVER_EXTEND_GRPC_PORT=<port>: ${e.cause?.message ?: e.message}"
            )
            throw e
        }
    }
    else
    {
        Logger.info(LogCategory.SYSTEM, "ServerExtend: gRPC transport is disabled by configuration")
    }

    // Start the AccelByte session staleness poller. Every 30s, every
    // URL the registry holds is re-validated against the AGS
    // platform; 404 means the platform deleted the session, so the
    // entry is removed. Cost is one SDK call per registered URL per
    // 30s, which is trivial for typical match volumes (<100). See
    // `.hermes/plans/2026-06-28_090808-server-extend-url-handover-registry.md`.
    val stalenessScope = CoroutineScope(SupervisorJob() + Dispatchers.IO)
    stalenessScope.launch {
        while (true)
        {
            try
            {
                ServerConnector.pollAccelByteSessionsForStaleness(ServerConnector.urlHandoverRegistry)
            }
            catch (err: Throwable)
            {
                Logger.warn(LogCategory.SYSTEM, "AccelByte session staleness poller crashed: ${err.message}")
            }
            delay(30_000L)
        }
    }

    // Start embedded Netty server with REST endpoints
    embeddedServer(Netty, host = "0.0.0.0", port = 7070) {
        serverModule()
    }.start(wait = true)
}

/**
 * Configures the Ktor application with REST endpoints and connection management.
 * 
 * Sets up JSON content negotiation, player connection management, and defines three
 * main endpoints:
 * - GET /player: Health check endpoint
 * - GET /events: Server-Sent Events streaming for real-time updates
 * - POST /rpc: JSON-RPC endpoint for client-server communication
 * 
 * Connection lifecycle events are logged for monitoring and debugging purposes.
 */

/**
 * Test-only hook. The most recently constructed [RestPlayerConnectionManager]
 * from a [serverModule] call is exposed here so the SSE/POST race integration
 * test in [ServerExtendHttpRaceTest] can set
 * [RestPlayerConnectionManager.registerDelayMillis] to force the race.
 * Production code never reads this. Marked `internal` to keep it module-scoped.
 */
@PublishedApi
internal var testHooks_lastConnectionManager: RestPlayerConnectionManager? = null

fun Application.serverModule()
{
    // Initialize RPC registry with automatic registration
    moduleRpcRegistry = ensureModuleRpcRegistry()
    
    // Configure JSON serialization for request/response handling
    install(ContentNegotiation) {
        json()
    }

    // Enable CORS for RPC/event clients such as the KVision frontend in dev/live
    install(CORS) {
        allowHeader(HttpHeaders.Accept)
        allowHeader(HttpHeaders.ContentType)
        allowHeader(HttpHeaders.Authorization)
        allowHeader(HttpHeaders.Origin)
        allowHeader(HttpHeaders.AccessControlRequestMethod)
        allowHeader(HttpHeaders.AccessControlRequestHeaders)
        allowMethod(HttpMethod.Options)
        allowMethod(HttpMethod.Get)
        allowMethod(HttpMethod.Post)
        allowNonSimpleContentTypes = true
        // Permit the dev front-end origins (with/without explicit ports)
        allowHost("localhost", schemes = listOf("http"))
        allowHost("127.0.0.1", schemes = listOf("http"))
        allowHost("localhost:4173", schemes = listOf("http"))
        allowHost("127.0.0.1:4173", schemes = listOf("http"))
        allowHost("localhost:8080", schemes = listOf("http"))
        allowHost("127.0.0.1:8080", schemes = listOf("http"))
        allowHost("127.0.0.1", schemes = listOf("http"))
        allowHost("127.0.0.1:8080", schemes = listOf("http"))
        allowHost("0.0.0.0", schemes = listOf("http"))
        allowHost(ConfigSource.property("accelbyte.local.properties", "AB_BASE_URL").removePrefix("https://").removePrefix("http://"), schemes = listOf("https"))
    }

    // Initialize connection management components
    val connectionManager = RestPlayerConnectionManager()
    // Expose the manager so the SSE/POST race integration test can set
    // [RestPlayerConnectionManager.registerDelayMillis] to deterministically
    // force the race. Production code never reads this back; only tests do.
    testHooks_lastConnectionManager = connectionManager
    val connectionCoordinator = RestServerConnectionCoordinator(
        manager = connectionManager,
        scope = CoroutineScope(coroutineContext),
        // The URL handover staleness listener: when a player vanishes
        // (closes the SSE channel mid-hand-off or after), every URL
        // the registry holds for a sessionId owned by that player
        // must be removed. Ownership is sourced from
        // ServerConnector.sessionIdsForPlayer. See
        // `.hermes/plans/2026-06-28_090808-server-extend-url-handover-registry.md`.
        urlHandoverRegistry = ServerConnector.urlHandoverRegistry,
        playerSessionResolver = { playerId -> ServerConnector.sessionIdsForPlayer(playerId) }
    ).apply {
        // Log player connection events for monitoring
        onConnected { session ->
            environment.log.info("Player ${session.playerId} connected")
        }
        onReconnected { session, _ ->
            environment.log.info("Player ${session.playerId} reconnected")
        }
        onDisconnected { playerId ->
            environment.log.info("Player $playerId disconnected")
        }
    }

    routing {
        /**
         * Health check endpoint for local development detection.
         * Simple endpoint that always returns 200 OK when server is running.
         */
        get("/player") {
            call.respond(HttpStatusCode.OK, mapOf("status" to "ok", "server" to "local"))
        }

        /**
         * Server-Sent Events endpoint for real-time streaming to clients.
         * Establishes persistent connection and streams RPC messages as SSE events.
         * Automatically generates playerId if not provided in query parameters.
         */
        get("/events") {
            // Extract or generate player ID for this connection
            val playerId = call.request.queryParameters["playerId"] ?: UUID.randomUUID().toString()
            val guestMode = call.request.queryParameters["guestMode"]?.toBoolean() == true
            // Origin tag for traffic classification (game client vs dedicated game server).
            // Defaults to GAME_CLIENT when absent for backwards compatibility with every
            // existing KVision / curl caller.
            val origin = RpcOrigin.fromValue(call.request.queryParameters["origin"])
            // AccelByte user id for the resume-game push (Phase B of the
            // resume-game-architecture plan). Optional: the live-mode
            // flow is fully wired but the client must be updated to pass
            // this on the SSE URL for the resumeAvailable push to fire.
            // When absent (existing dev callers, or Phase C clients that
            // have not yet been updated) the push is skipped silently.
            val accelbyteId = call.request.queryParameters["accelbyteId"]?.takeIf { it.isNotBlank() } ?: ""

            if (guestMode)
            {
                ExtendConfig.debugMode = true
                Logger.info(LogCategory.NETWORK, "SSE /events: Guest mode detected for playerId=$playerId, debugMode enabled")
            }

            environment.log.info("SSE /events request received for playerId=$playerId (guestMode=$guestMode, origin=$origin)")
            Logger.info(LogCategory.NETWORK, "SSE /events request for playerId=$playerId (guestMode=$guestMode, origin=$origin)")

            // Register session SYNCHRONOUSLY before responding. The origin tag
            // is propagated to the per-session telemetry sink via the manager
            // so the in-process RpcUsageTracker can count this connection's
            // future inbound RPCs as the correct origin.
            val registration = connectionManager.register(playerId, origin)
            val session = registration.session
            environment.log.info("SSE /events registration outcome for playerId=$playerId: ${registration.outcome}")

            // Broadcast connection event to other players
            connectionManager.broadcastConnectionEvent(playerId, ConnectionStatus.CONNECTED)

            // BUG 26 (2026-06-27, revised): the resume-availability PUSH
            // still fires on connect (so the dialog appears after login,
            // per the user's stated spec) — but the main server's AUTO-RESTORE
            // is unconditionally disabled. The push tells the client "you
            // have a saved game, show the dialog." The dialog's Resume
            // button is the only path that triggers the actual restore via
            // the explicit `server.restoreRunningGame` RPC handler in
            // GameRestoreRpcHandlers.
            //
            // The previous version of this comment claimed both push AND
            // restore should be disabled. That created a chicken-and-egg:
            // the dialog never appeared, so the user couldn't click Resume,
            // so no restore ever happened. The correct invariant is:
            //   - PUSH on connect (shows the dialog)
            //   - NEVER auto-restore (restore only on explicit Resume click)
            //
            // The accelbyteId parameter is parsed above for this push and
            // for logging / audit trails.
            if (accelbyteId.isNotBlank())
            {
                triggerSseResumePush(accelbyteId)
            }

            // Configure SSE headers for streaming
            call.response.headers.append(HttpHeaders.CacheControl, "no-cache")
            call.response.headers.append(HttpHeaders.ContentType, ContentType.Text.EventStream.toString())
            
            try
            {
                // Stream outgoing messages as SSE data events
                call.respondTextWriter(contentType = ContentType.Text.EventStream) {
                // Send immediate confirmation that session is ready
                val sessionReadyPayload = RpcMessage.Notification(method = "session.ready").toJson(RpcJson)
                write("data: $sessionReadyPayload\n\n")
                flush()
                Logger.debug(LogCategory.NETWORK, "SSE /events streaming started for playerId=$playerId")
                    
                    session.outgoingFlow().collect { payload ->
                        environment.log.debug("Sending SSE payload to playerId=$playerId: ${payload.take(200)}")
                        write("data: ")
                        write(payload)
                        write("\n\n")
                        flush()
                    }
                }
            }
            finally
            {
                // Clean up connection and notify other players
                connectionManager.deregister(playerId, session)
                connectionManager.broadcastConnectionEvent(playerId, ConnectionStatus.DISCONNECTED)
            }
        }

        /**
         * JSON-RPC endpoint for client-server communication.
         * Validates player connection and processes RPC messages through the registry.
         * Requires playerId query parameter and active player session.
         */
        post("/rpc") {
            // Validate required playerId parameter
            val playerId = call.request.queryParameters["playerId"]
            environment.log.info("RPC POST received for playerId=$playerId")
            Logger.info(LogCategory.NETWORK, "RPC POST request for playerId=$playerId")
            
            if(playerId.isNullOrBlank())
            {
                environment.log.warn("RPC POST rejected: missing playerId parameter")
                Logger.warn(LogCategory.NETWORK, "RPC POST rejected: missing playerId parameter")
                return@post call.respond(HttpStatusCode.BadRequest, "playerId query parameter is required")
            }
            
            // Verify player has active session. We use `awaitSession` rather
            // than `findSession` because the POST and the SSE GET arrive on
            // independent Ktor coroutines, and the POST can run before the
            // SSE handler reaches `connectionManager.register(playerId)`.
            // The 1s default budget bridges the observed ~400us SSE
            // registration window with margin while still failing fast on a
            // genuinely disconnected client.
            val session = connectionManager.awaitSession(
                playerId = playerId,
                timeoutMillis = 1_000,
                pollIntervalMillis = 25,
            )
            if(session == null)
            {
                environment.log.warn("RPC POST rejected: player $playerId not connected")
                return@post call.respond(HttpStatusCode.NotFound, "player not connected")
            }
            
            // Process RPC payload through session handler
            val raw = call.receiveText()
            environment.log.info("RPC /rpc request received for playerId=$playerId, payload length=${raw.length}")
            Logger.debug(LogCategory.NETWORK, "RPC payload for $playerId (length=${raw.length}): $raw")
            try {
                session.handleRpcPayload(raw, moduleRpcRegistry, call.application.environment)
            } catch (e: Exception) {
                Logger.error(LogCategory.NETWORK, "Error handling RPC payload for $playerId: $${e.message}")
                e.printStackTrace()
            }
            call.respond(HttpStatusCode.Accepted)
        }
    }
}

/**
 * Processes incoming RPC payload for a specific player session.
 * 
 * Parses the raw JSON payload into RPC messages and dispatches them through
 * the RPC registry. Handles requests, notifications, responses, and streaming
 * operations with proper context and error handling.
 * 
 * @param raw Raw JSON string containing the RPC message
 * @param rpcRegistry Registry containing RPC method handlers
 * @param env Application environment for logging and configuration
 */
private suspend fun RestPlayerSession.handleRpcPayload(
    raw: String,
    rpcRegistry: RpcRegistry,
    env: ApplicationEnvironment
    )
    {
        // Parse raw JSON into structured RPC message
        val message = try {
            raw.toRpcMessage(RpcJson)
        } catch (e: Exception) {
            Logger.error(LogCategory.NETWORK, "Failed to parse RPC message for $playerId: $${e.message}")
            return
        }

        when(message)
        {
            is RpcMessage.Request ->
            {
                Logger.debug(LogCategory.NETWORK, "Processing RPC request ${message.method} from playerId=${playerId}")
                env.log.info("Processing RPC request ${message.method} for playerId=${playerId}")
                // Handle RPC request with response expected
                val context = RpcCallContext(
                    connectionId = playerId,
                sender = { outbound -> sendRpcMessage(outbound) }
            )
            val response = try {
                rpcRegistry.dispatch(message, context)
            } catch (e: Exception) {
                Logger.error(LogCategory.NETWORK, "Exception during RPC dispatch of ${message.method} for $playerId: $${e.message}")
                RpcMessage.Response(id = message.id, error = org.ttt.autogenesis.network.RpcError(500, e.message ?: "Internal error"))
            }
            
            if (response?.error != null)
            {
                Logger.error(LogCategory.NETWORK, "RPC dispatch returned error for ${message.method}: ${response.error}")
            }
            
            response?.let { sendRpcMessage(it) }
        }
            is RpcMessage.Notification ->
            {
                Logger.debug(LogCategory.NETWORK, "Processing RPC notification ${message.method} for playerId=${playerId}")
                env.log.info("Processing RPC notification ${message.method} for playerId=${playerId}")
                // Handle RPC notification (no response expected)
            val context = RpcCallContext(
                connectionId = playerId,
                sender = { outbound -> sendRpcMessage(outbound) }
            )
            rpcRegistry.dispatchNotification(message, context)
        }
            is RpcMessage.Response ->
            {
                Logger.debug(LogCategory.NETWORK, "Processing RPC response ${message.id} for playerId=${playerId}")
                env.log.info("Processing RPC response ${message.id} for playerId=${playerId}")
                // Handle response to previous client request
            invoker.handleResponse(message)
        }
        is RpcMessage.StreamChunk ->
        {
            Logger.debug(LogCategory.NETWORK, "Handling stream chunk ${message.id} from playerId=${playerId}")
            invoker.handleStreamChunk(message)
        }
        is RpcMessage.StreamCancel ->
        {
            Logger.debug(LogCategory.NETWORK, "Handling stream cancel ${message.id} from playerId=${playerId}")
            if(!invoker.handleStreamCancel(message))
            {
                rpcRegistry.cancelStream(message.id)
            }
        }
        else -> Unit // Ignore unknown message types
    }
}


/**
 * Triggers the resume-game push service when the SSE /events connection
 * carries a non-blank `accelbyteId` query parameter.
 *
 * BUG 26 (2026-06-27, revised): this helper DOES still fire on SSE connect
 * — that's what makes the dialog appear after login (per the user's stated
 * spec). What changed is that the main server's AUTO-RESTORE on WS
 * connect is now unconditionally disabled. So:
 *   - PUSH on connect → dialog appears (this helper)
 *   - NEVER auto-restore → no snapshot apply until user clicks Resume
 *
 * The push and the restore are now decoupled. The push is "you have a
 * saved game, show the dialog." The restore only fires from the explicit
 * `server.restoreRunningGame` RPC, which is invoked from
 * MainMenu.beginResumeSession after the user clicks Resume in
 * ResumeOrNewDialog.
 *
 * Structural test
 * `server-extend/src/test/kotlin/org/ttt/autogenesis/serverextend/SseResumePushDisabledTest.kt`
 * was deleted because its old assertions ("helper must be gone") no longer
 * match this revised spec. The new test at
 * `server-extend/src/test/kotlin/org/ttt/autogenesis/serverextend/SseResumePushPushOnConnectTest.kt`
 * asserts the helper IS still present and IS called from the SSE handler.
 */
internal fun triggerSseResumePush(accelbyteId: String)
{
    if (accelbyteId.isBlank())
    {
        return
    }
    ResumeAvailabilityPushService.checkAndPush(accelbyteId)
}
