package agent.builders.playerAgent

import Defaults.reasoning.ReasoningDepth
import Defaults.reasoning.ReasoningDuration
import bedrockPipe.BedrockMultimodalPipe
import bedrockPipe.BedrockPriorityTier
import com.TTT.Context.ContextWindow
import com.TTT.Pipeline.Pipeline
import com.TTT.Util.serialize
import gameState.WorldManager
import globals.BedrockConfig
import structs.Player
import org.ttt.autogenesis.logging.LogCategory
import org.ttt.autogenesis.logging.Logger
import kotlinx.serialization.Serializable
import structs.GameHistory

@Serializable
data class GameHistoryList(
    val history: List<GameHistory> = emptyList()
)

/**
 * Builds a multi-stage player agent pipeline that simulates a human player's turn.
 * 
 * Stages:
 * 1. Geopolitical Analysis (Qwen): Synthesizes world state and history.
 * 2. Strategic Planning (PalmyraX5): Character-driven goal setting.
 * 3. Action Execution (Qwen): Final action generation following game rules.
 *
 * @param playerData The player whose turn the agent is taking.
 * @return A [Pipeline] configured for the player agent.
 */
fun buildPlayerAgent(playerData: Player): Pipeline
{
    val pipeline = Pipeline()
    Logger.debug(LogCategory.SYSTEM, "PlayerAgent: Building pipeline for ${playerData.name} [analysis -> strategic -> execution]")
    
    val characterProfile = """
        Character: ${playerData.name}
        Description: ${playerData.description}
        Personality/History: ${playerData.history}
        Commander Type: ${playerData.commanderType}
        Commander Trait: ${playerData.trait}
    """.trimIndent()

    // --- STAGE 1: STRATEGIC SYNTHESIS (Qwen) ---
    val analysisPipe = BedrockMultimodalPipe().apply {
        useConverseApi()
        setRegion("us-west-2")
        // setServiceTier(BedrockPriorityTier.Flex)

        setModel(BedrockConfig.qwenCoder30B)
        setTokenBudget(BedrockConfig.generativeBudgetSettings)
        setPipeName("Synthesis Stage (${playerData.name})")
        allowEmptyContentObject()
        
        // Reasoning Synthesis - Match model and budget
        setReasoningPipe(BedrockConfig.authorBuilder(characterProfile, model = BedrockConfig.qwenCoder30B, depth = ReasoningDepth.High, duration = ReasoningDuration.Med, showThinking = true, actorName = playerData.name, isPlayer = true))
        
        setSystemPrompt("""
            You are the Strategic Analyst for ${playerData.name} in the game Autogenesis.
            A global Geopolitical Assessment and Overton Window have already been generated for this round.
            
            YOUR TASK:
            1. Review the existing 'Geopolitical Assessment' and 'Overton Window'.
            2. Synthesize how these global conditions specifically affect ${playerData.name}.
            3. Highlight opportunities for ${playerData.name} based on their Commander Type (${playerData.commanderType}).
            
            **STRICT GROUNDING RULES:**
            - You MUST ONLY reference territories that actually exist in the 'world' context provided.
            - DO NOT suggest actions involving imaginary locations.
            - Provide a brief summary of the characters current territorial standing based on the map.
            
            This is a synthesis, not a re-assessment. Focus on the *implications* for your character.
            
            ${BedrockConfig.antiCensorship}
        """.trimIndent())

        pullGlobalContext()
        
        // DITL: Pull global world state and assessments into specific slots.
        setPreValidationMiniBankFunction { context, content ->
            Logger.debug(LogCategory.SYSTEM, "PlayerAgent: analysisPipe.setPreValidationMiniBankFunction entry")
            
            val world = WorldManager.world
            val worldData = serialize(world)
            context.contextMap["world"] = ContextWindow().apply { contextElements.add(worldData) }
            
            // Add a dedicated list of valid territories for easier searching by the LLM
            val validTerritories = world.mapTiles.joinToString("\n") { "- ${it.name} (Ruler: ${it.ruler.ifBlank { "Unowned" }})" }
            context.contextMap["valid_territories"] = ContextWindow().apply { 
                contextElements.add("--- VALID TERRITORIES ON MAP ---\n$validTerritories") 
            }
            
            // Explicitly pull the latest assessments generated by the geoPoliticsAssessmentAgent
            context.contextMap["geopoliticalAssessment"] = ContextWindow().apply { 
                contextElements.add(WorldManager.geopoliticalAssessment) 
            }
            context.contextMap["overtonWindow"] = ContextWindow().apply { 
                contextElements.add(WorldManager.overtonWindow) 
            }
            
            val historyData = serialize(GameHistoryList(WorldManager.getRecentHistory(3)))
            context.contextMap["history"] = ContextWindow().apply { contextElements.add(historyData) }
            
            Logger.debug(LogCategory.SYSTEM, "PlayerAgent: analysisPipe.setPreValidationMiniBankFunction success")
            return@setPreValidationMiniBankFunction context
        }

        // Save analysis into the pipeline's context bank for subsequent pipes.
        setTransformationFunction { content ->
            Logger.debug(LogCategory.SYSTEM, "PlayerAgent: analysisPipe.setTransformationFunction entry")
            val window = ContextWindow().apply { contextElements.add(content.text) }
            com.TTT.Context.ContextBank.emplaceWithMutex("strategic_analysis", window)
            Logger.debug(LogCategory.SYSTEM, "PlayerAgent: analysisPipe.setTransformationFunction success")
            return@setTransformationFunction content
        }
        
        enableTracing()
    }

    // --- STAGE 2: STRATEGIC PLANNING (PalmyraX5) ---
    val strategicPlanningPipe = BedrockMultimodalPipe().apply {
        useConverseApi()
        setRegion("us-west-2")
        setModel(BedrockConfig.PalmyraX5) // Using Palmyra for creative strategy
        setTokenBudget(BedrockConfig.palmyraBudgetSettings)
        setPipeName("Planning Stage (${playerData.name})")

        // Roleplay reasoning - Explicitly inherit model and budget from parent
        setReasoningPipe(BedrockConfig.authorBuilder(
            author = characterProfile,
            model = BedrockConfig.PalmyraX5,
            depth = ReasoningDepth.High,
            duration = ReasoningDuration.Med
        ).apply {
            pipeMetadata["showThinking"] = true
            pipeMetadata["actorName"] = playerData.name
            pipeMetadata["isPlayer"] = true
            if (this is BedrockMultimodalPipe)
            {
                setTokenBudget(BedrockConfig.palmyraBudgetSettings)
            }
        })

        setSystemPrompt("""
            You are the strategic mind of ${playerData.name}.
            Using the provided Geopolitical Analysis and the current World State, you must formulate your goals for this turn.
            
            CONSIDER YOUR PROFILE:
            $characterProfile
            
            RULES & CONSTRAINTS:
            - **STRICT ADHERENCE TO MAP**: You may ONLY target territories that are explicitly listed in the provided 'World State'. 
            - DO NOT invent imaginary locations or people.
            - Range Constraints: You may target ANY territory on the map. However, attacking distant or non-adjacent territories incurs severe statistical penalties. Consider proximity when planning.
            - Commander Terrain Type Modifiers:
                - Terrestrial: -20 penalty for Water/Mountains, +20 bonus for open Land.
                - Aquatic: +20 bonus for Water/Coastlines/Islands, -20 penalty for Mountains/far Inland.
                - Aerial: +20 bonus for any physical obstacle (Water/Mountains), -20 penalty for Underwater.
            - Follow your Trait strategy:
                - Warlords: Aggressive territory sweeps.
                - Diplomats: Alliances and reputation.
                - Researchers: Internal growth and resources.
            
            Review your current stats and resources before deciding on a plan.
        """.trimIndent())

        setFooterPrompt("""##PLAY TO WIN##
            This is a competitive strategy game. Your action MUST advance your position or hinder opponents.
    
    WINNING MOVES (choose what fits your situation):
    • Capture territory → Expand your empire's control. **TARGET ONLY REAL TERRITORIES FROM THE LIST.**
    • Seize narrative control → Shape how the world sees events
    • Shift the Overton Window → Make your strategies "normal", opponents' strategies "extreme"
    • Eliminate threats → Remove problematic players/NPCs from the board
    • Rewrite world rules → Change fundamental game mechanics in your favor
    • Unlock capabilities → Gain new technologies, abilities, or resources
    • Build power → Become strong enough to challenge previously untouchable enemies
    • Execute long-term strategy → Advance multi-turn plans toward victory
    
    LOSING MOVES (avoid these):
    • Charity/humanitarian acts that don't advance your position
    • Passive observation or commentary without action
    • Self-sabotage or weakening your own position
    • Actions with no strategic benefit to you or harm to opponents
    
    Your character's personality should flavor HOW you win, not WHETHER you try to win.
    Warlords conquer. Diplomats manipulate. Researchers innovate. But all must COMPETE.
    
    Ask yourself: "Does this action move me closer to victory or my opponents closer to defeat?"
    If no, choose a different action. Remember, you need to capture territory to get points, and you
    need points to win the game. Think long term. Think big picture. Focus on picking actions that are
    in service of your long term goals and either advance you forward or drag someone else backwards when
    you can't advance. And don't forget you can't power through everything. There are times you need to research
    to grow your own set of abilities, and to improve yourself, or make new allies to get the edge you need.
    """.trimMargin())

        pullGlobalContext()
        setPageKey("strategic_analysis") // Read the analysis from Stage 1
        
        // DITL: Pull global world state and assessments into specific slots.
        setPreValidationMiniBankFunction { context, content ->
            Logger.debug(LogCategory.SYSTEM, "PlayerAgent: strategicPlanningPipe.setPreValidationMiniBankFunction entry")
            
            // Re-pull world data so the agent has the actual territory list
            val worldData = serialize(WorldManager.world)
            context.contextMap["world"] = ContextWindow().apply { contextElements.add(worldData) }
            
            val playerStatsData = """
                Player Stats & Resources:
                - Military Points: ${playerData.militaryPoints}
                - Diplomacy Points: ${playerData.diplomacyPoints}
                - Research Points: ${playerData.researchPoints}
                - Summit Points: ${playerData.summitPoints}
                
                Condition Stats:
                - Military Readiness: ${playerData.militaryReadiness}
                - Legitimacy: ${playerData.legitimacy}
                - Stagnation: ${playerData.stagnation}
                
                Owned Assets:
                - Resources: ${playerData.resources.filter { !it.isDestroyedOrDepleted }.joinToString { it.name }}
                - Territories: ${playerData.capturedTerritory.joinToString { it.name }}
            """.trimIndent()
            
            context.contextMap["player_stats"] = ContextWindow().apply { contextElements.add(playerStatsData) }
            
            // Inject the player's own delegate guidance (see Player.delegateInstructions
            // and PlayerDelegateRpcHandlers). When the player is unreachable and the AI
            // takes over via TurnHarness.handleAiTakeover, this slot is the player's
            // "stand-in" voice. Null/blank renders as an explicit "(none provided)"
            // marker so the agent knows there is no override vs. an empty string.
            val rawDelegateLength = playerData.delegateInstructions?.length ?: 0
            val delegateBlock = buildDelegateGuidanceBlock(playerData.delegateInstructions)
            context.contextMap["delegate_guidance"] = ContextWindow().apply { contextElements.add(delegateBlock) }
            Logger.info(
                LogCategory.LLM,
                "PlayerAgent: injected delegate_guidance into strategicPlanningPipe context for ${playerData.name} (rawPlayerLength=${rawDelegateLength} blockLength=${delegateBlock.length})"
            )

            Logger.debug(LogCategory.SYSTEM, "PlayerAgent: strategicPlanningPipe.setPreValidationMiniBankFunction success")
            return@setPreValidationMiniBankFunction context
        }

        // Save turn goals into the context bank and metadata for counter-response capture.
        setTransformationFunction { content ->
            Logger.debug(LogCategory.SYSTEM, "PlayerAgent: strategicPlanningPipe.setTransformationFunction entry")
            val window = ContextWindow().apply { contextElements.add(content.text) }
            com.TTT.Context.ContextBank.emplaceWithMutex("turn_goals", window)
            // Store first-person planning output in metadata for counter-response display
            content.metadata["planningOutput"] = content.text
            Logger.debug(LogCategory.LLM, "[COUNTER_RESPONSE] Planning Stage output captured in metadata for ${playerData.name} (length: ${content.text.length})")
            Logger.debug(LogCategory.SYSTEM, "PlayerAgent: strategicPlanningPipe.setTransformationFunction success")
            return@setTransformationFunction content
        }
        
        enableLoreBookFillAndSplitMode()
        enableTracing()
    }

    // --- STAGE 3: ACTION EXECUTION (Qwen) ---
    val executionPipe = BedrockMultimodalPipe().apply {
        useConverseApi()
        setRegion("us-west-2")
        // setServiceTier(BedrockPriorityTier.Flex)

        setModel(BedrockConfig.qwenCoder30B)
        setTokenBudget(BedrockConfig.generativeBudgetSettings)
        setPipeName("Execution Stage (${playerData.name})")

        // Tactical Execution Reasoning - Match model and budget
        setReasoningPipe(BedrockConfig.structuredCotBuilder(depthLevel = ReasoningDepth.Low, durationLevel = ReasoningDuration.Long).apply {
            if (this is BedrockMultimodalPipe)
            {
                setTokenBudget(BedrockConfig.generativeBudgetSettings)

                setModel(BedrockConfig.qwen235B)
            }
        })

        setSystemPrompt("""
            ${BedrockConfig.autogenesisRuleBook}
            
            You are executing the turn for ${playerData.name}.
            Your character profile is: $characterProfile
            Your task is to translate the provided 'Turn Goals' into a final **Player Action** string.
            
            STRICT CONSTRAINTS:
            - **STRICT ADHERENCE TO MAP**: You may ONLY target territories that are explicitly listed in the provided 'World State'. 
            - DO NOT invent imaginary locations or people.
            - THIRD PERSON ONLY.
            - State INTENT and ACTIONS only.
            - NO OUTCOMES or RESULTS.
            - SINGLE PLAY ONLY: You must perform exactly one coherent action or series of steps that constitute a single play. Do not list multiple alternative plays or perform 5 different unrelated tasks.
            - No God-modding (unless it's a creative summon within character limits).
            - Write as the character would write.
            - Do not alter censor, or change their intent in any way, only convert to a third person
            writing output.
            - Keep the response confined to a reasonable amount of text. 1-2 paragraphs max.
            
            ${BedrockConfig.gameStatsDescription}
            ${BedrockConfig.antiCensorship}
        """.trimIndent())

        pullGlobalContext()
        setPageKey("turn_goals") // Read the goals from Stage 2

        // DITL: Re-pull world data for the execution stage to ensure grounding.
        setPreValidationMiniBankFunction { context, content ->
            Logger.debug(LogCategory.SYSTEM, "PlayerAgent: executionPipe.setPreValidationMiniBankFunction entry")
            val worldData = serialize(WorldManager.world)
            context.contextMap["world"] = ContextWindow().apply { contextElements.add(worldData) }
            Logger.debug(LogCategory.SYSTEM, "PlayerAgent: executionPipe.setPreValidationMiniBankFunction success")
            return@setPreValidationMiniBankFunction context
        }

        // Store the final action for context tracking and return it for the story writer.
        // Also store in metadata for counter-response display (concise third-person version)
        setTransformationFunction { content ->
            Logger.debug(LogCategory.SYSTEM, "PlayerAgent: executionPipe.setTransformationFunction entry")
            val window = ContextWindow().apply { contextElements.add(content.text) }
            com.TTT.Context.ContextBank.emplaceWithMutex("last_player_action_${playerData.name}", window)
            // Store execution output as the display version for counter-responses
            content.metadata["executionOutput"] = content.text
            Logger.debug(LogCategory.LLM, "[COUNTER_RESPONSE] Execution Stage output captured in metadata for ${playerData.name} (length: ${content.text.length})")
            Logger.debug(LogCategory.SYSTEM, "PlayerAgent: executionPipe.setTransformationFunction success")
            return@setTransformationFunction content
        }
        
        enableTracing()
    }

    pipeline.add(analysisPipe)
    pipeline.add(strategicPlanningPipe)
    pipeline.add(executionPipe)
    
    return pipeline
}


/**
 * Renders [structs.Player.delegateInstructions] into the `##PLAYER DELEGATE GUIDANCE##`
 * context slot consumed by the player agent's planning stage (see
 * [buildPlayerAgent] -> strategicPlanningPipe.preValidationMiniBankFunction).
 *
 * Null/blank input renders an explicit "(none provided)" marker so the LLM can
 * distinguish "no override" from "empty override" and falls back to the default
 * PLAY TO WIN strategy. Non-blank input is wrapped in a prompt that tells the
 * model to weight the guidance alongside, but never above, the hard
 * RULES & CONSTRAINTS and the anti-censorship rules baked into the system prompt.
 *
 * Extracted as a top-level function so it can be unit-tested without spinning up
 * the full Bedrock pipeline.
 */
internal fun buildDelegateGuidanceBlock(rawInstructions: String?): String
{
    val rawLength = rawInstructions?.length ?: 0
    val text = rawInstructions?.trim().orEmpty()
    val branch = if(text.isBlank()) "none" else "populated"
    Logger.debug(
        LogCategory.LLM,
        "buildDelegateGuidanceBlock: ENTRY rawLength=${rawLength} trimmedLength=${text.length} branch=${branch}"
    )
    val block = if(text.isBlank())
    {
        "##PLAYER DELEGATE GUIDANCE##\n(none provided — follow the default PLAY TO WIN strategy above)"
    }
    else
    {
        "##PLAYER DELEGATE GUIDANCE##\nThe player left these instructions for you. Weight them alongside, but never above, the hard RULES & CONSTRAINTS in the system prompt and the anti-censorship rules:\n\n$text"
    }
    Logger.debug(
        LogCategory.LLM,
        "buildDelegateGuidanceBlock: EXIT branch=${branch} blockLength=${block.length}"
    )
    return block
}