package org.ttt.autogenesis.network

/**
 * Manages a REST-based RPC connection using SSE for incoming and HTTP POST for outgoing messages.
 *
 * Provides a high-level abstraction for REST RPC communication that can be used across all modules.
 * Uses the expect/actual pattern for platform-specific implementations.
 */
expect object RestRpcBridge
{
    /**
     * Returns the active invoker after a successful connection.
     */
    val rpcInvoker : RpcInvoker?

    /**
     * Determines whether an active connection exists.
     */
    val isConnected : Boolean

    /**
     * Determines whether the session is ready for RPC calls.
     */
    val isSessionReady : Boolean

    /**
     * Registers client-side RPC handlers so the server can invoke them.
     *
     * @param block Configuration block executed against the shared registry.
     */
    fun registerHandlers(block : RpcRegistry.() -> Unit)

    /**
     * Register a callback to be invoked once the SSE connection is established.
     * If already connected, the callback is invoked immediately.
     * The callback is cleared after invocation.
     */
    fun onConnected(fn: () -> Unit)

    /**
     * Connects to the specified REST endpoint using the provided player ID.
     *
     * Calling `connect` with the same [playerId] and [accelbyteId] while a
     * session is already active is a no-op (the bridge is idempotent on
     * the pair). Supplying a different [accelbyteId] rebinds the SSE
     * inbound to the authenticated user so server-side player resolution
     * works even after login.
     *
     * ## Caller contract — MUST AWAIT THIS FUNCTION
     *
     * `connect(...)` is `suspend` and returns ONLY after the new SSE
     * channel is established AND the old client (if any) has been fully
     * torn down — including `drainInFlightRequests()` which cancels any
     * pending requests on the old client with a
     * [RestRpcClientClosedException]. Callers that need to swap the
     * bridge mid-flight (e.g. the post-login rebind in
     * `LoginWidgets.startLogin`) MUST `await` this function inline
     * rather than wrapping it in `launch { ... }`. Wrapping the rebind
     * in a fire-and-forget coroutine reintroduces the race:
     *
     *   1. Caller fires `launch { bridge.connect(accelbyteId=X) }` and
     *      immediately reads `bridge.rpcInvoker` and issues an RPC.
     *   2. The rebind's `client?.close()` cancels the old pending
     *      request with [RestRpcClientClosedException].
     *   3. The new RPC either races against the in-flight close (and
     *      lands on the dying old invoker) or sees a null invoker if
     *      the swap hadn't finished.
     *
     * Awaiting inline is atomic from the caller's perspective: by the
     * time the next line runs, [rpcInvoker] (and
     * [ServerExtendBridge.rpcInvoker][org.ttt.autogenesis.kvisionapp.ServerExtendBridge.rpcInvoker])
     * is the X-bound client.
     *
     * @param playerId Optional player ID; a stable one is generated by default.
     * @param baseUrl Base server URL for REST RPC connection.
     * @param autoReconnect Reconnect on transient SSE drops.
     * @param suppressSseLogs Quiet the verbose SSE log lines.
     * @param isGuestMode Marks the session as guest so the server can apply
     *                    guest-only policies.
     * @param accelbyteId Optional AccelByte user ID; the bridge short-circuits
     *                    when the existing session already matches it, which
     *                    prevents the post-login reconnect from tearing down
     *                    an in-flight request.
     */
    suspend fun connect(
        playerId : String = generatePlayerId(),
        baseUrl : String,
        autoReconnect : Boolean = true,
        suppressSseLogs : Boolean = true,
        isGuestMode : Boolean = false,
        accelbyteId : String? = null,
        /**
         * Origin tag for this connection. Carried on the wire as
         * `?origin=server` so the receiver can distinguish
         * game-client traffic from game-server traffic (see
         * [RpcOrigin]). Defaults to [RpcOrigin.GAME_CLIENT] for
         * backwards compatibility with every existing caller.
         */
        origin : RpcOrigin = RpcOrigin.GAME_CLIENT
    )

    /**
     * Disconnects and releases any held client resources.
     */
    /**
     * Wait for any in-flight RPC requests to drain (receive their
     * response or fail). Bounded by [timeoutMillis]. Used by
     * callers that are about to close the bridge and don't want
     * to drop a request whose SSE response is still in transit.
     *
     * @param timeoutMillis Max time to wait. Default 2s — well above
     *   p99 SSE delivery on localhost and tight enough to surface
     *   a wedged SSE channel in the same session.
     * @return True if all requests drained, false on timeout.
     */
    suspend fun awaitInFlightRequests(timeoutMillis: Long = 2_000L): Boolean

    suspend fun close()

    /**
     * Generates a unique player ID for the connection.
     */
    fun generatePlayerId() : String
}