// @generated by protoc-gen-es v1.10.1 with parameter "target=js"
// @generated from file rpc_bridge.proto (package autogenesis.rpc, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message autogenesis.rpc.RpcEnvelope
 */
export const RpcEnvelope = /*@__PURE__*/ proto3.makeMessageType(
  "autogenesis.rpc.RpcEnvelope",
  () => [
    { no: 1, name: "payload", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

