// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=js"
// @generated from file rpc_bridge.proto (package autogenesis.rpc, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { RpcEnvelope } from "./rpc_bridge_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service autogenesis.rpc.RpcBridge
 */
export const RpcBridge = {
  typeName: "autogenesis.rpc.RpcBridge",
  methods: {
    /**
     * @generated from rpc autogenesis.rpc.RpcBridge.Stream
     */
    stream: {
      name: "Stream",
      I: RpcEnvelope,
      O: RpcEnvelope,
      kind: MethodKind.BiDiStreaming,
    },
    /**
     * @generated from rpc autogenesis.rpc.RpcBridge.Invoke
     */
    invoke: {
      name: "Invoke",
      I: RpcEnvelope,
      O: RpcEnvelope,
      kind: MethodKind.Unary,
    },
  }
};
