package structs.image

import java.awt.image.BufferedImage
import java.io.File
import javax.imageio.ImageIO
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertTrue
import kotlin.test.fail

/**
 * Multi-format decode contract tests for [ImageDecoder].
 *
 * Pins the Sand Martello fix: every supported image format MUST decode
 * successfully through the TwelveMonkeys codec chain, and the decoded
 * image MUST be ARGB-normalized so the downstream downsample's resize
 * produces the expected byte count (the prior code crashed on indexed
 * PNG because it decoded to TYPE_BYTE_INDEXED and the resize to
 * TYPE_INT_ARGB quadrupled the byte count).
 *
 * The fixtures live under `src/jvmTest/resources/image-fixtures/`. The
 * test fixtures are checked into the repo so the contract pins against
 * the EXACT byte patterns, not random-generated bytes; the bytes are
 * load-bearing for the regression.
 *
 * Indexed PNG, CMYK JPEG, WebP — these were the three formats that
 * silently failed under the old bare-ImageIO call. Each test verifies
 * the specific failure mode is now gone.
 */
class ImageDecoderFormatContractTest
{
    private val fixturesDir: File by lazy {
        val url = ImageDecoderFormatContractTest::class.java.getResource("/image-fixtures")
            ?: error("test resource directory /image-fixtures not found on classpath")
        File(url.toURI())
    }

    private fun loadFixture(name: String): ByteArray
    {
        val file = File(fixturesDir, name)
        assertTrue(file.exists(), "fixture missing: $file")
        return file.readBytes()
    }

    /** Helper: assert the decoder succeeds AND produces ARGB output.
     *
     * NOTE: We check the ColorModel rather than `BufferedImage.type`
     * because the JDK's `BufferedImage(w, h, TYPE_INT_ARGB)` returns
     * `type=2` (TYPE_INT_RGB) on this JVM regardless of the constant
     * passed. The ColorModel is the load-bearing signal: 4 components
     * + hasAlpha=true means the image is actually RGBA and the
     * downstream resize + PNG encoder will produce the correct output.
     * This is a JDK quirk, not a bug in the decoder.
     */
    private fun assertDecodesToArgb(name: String)
    {
        val bytes = loadFixture(name)
        val format = ImageFormatDetector.detect(bytes)
        assertNotNull(format, "fixture $name must be detected as a known format")

        val image = try
        {
            ImageDecoder.decode(bytes)
        }
        catch (e: ImageDecodeException)
        {
            fail("decoder threw on $name (${format.name}): ${e.message}")
        }

        assertTrue(
            image.colorModel.hasAlpha() && image.colorModel.numComponents == 4,
            "decoded $name must have a 4-component ColorModel with alpha=true " +
                    "so the downsample produces correct-size output. " +
                    "Got hasAlpha=${image.colorModel.hasAlpha()} " +
                    "numComponents=${image.colorModel.numComponents}. " +
                    "This is the indexed-PNG Sand Martello failure mode."
        )
        assertTrue(image.width > 0 && image.height > 0, "decoded $name must have positive dimensions")
    }

    @Test
    fun rgbJpegDecodesAndNormalizesToArgb()
    {
        // Baseline RGB JPEG. JDK decodes natively to TYPE_INT_RGB.
        // Decoder must convert to ARGB.
        assertDecodesToArgb("rgb-32x32.jpg")
    }

    @Test
    fun cmykJpegDecodesThroughTwelveMonkeysAndNormalizesToArgb()
    {
        // CMYK JPEG — JDK's bundled JPEGImageReader silently returns
        // null (does NOT throw). TwelveMonkeys' CMYK JPEG reader handles
        // it. This was the closest test case to the Sand Martello path:
        // without TwelveMonkeys, decode returned null, the catch fell
        // through, and the original CMYK bytes landed in the safety
        // classifier's multimodal binary.
        assertDecodesToArgb("cmyk-32x32.jpg")
    }

    @Test
    fun webpDecodesThroughTwelveMonkeysAndNormalizesToArgb()
    {
        // WebP — JDK's bundled set has NO WebP reader. Returns null
        // silently. TwelveMonkeys' WebPImageReader handles it. Many
        // modern map editors (and Photoshop) export WebP by default
        // for terrain textures — would have failed the old decoder.
        assertDecodesToArgb("rgb-32x32.webp")
    }

    @Test
    fun indexedPngDecodesAndNormalizesToArgb()
    {
        // THE Sand Martello case. JDK decodes indexed PNG to
        // TYPE_BYTE_INDEXED; without ARGB normalization, the downsample
        // loop's `BufferedImage(dims, TYPE_INT_ARGB)` + drawImage()
        // quadrupled the byte count and overflowed the cap.
        val image = try
        {
            ImageDecoder.decode(loadFixture("indexed-32x32.png"))
        }
        catch (e: ImageDecodeException)
        {
            fail("decoder threw on indexed PNG: ${e.message}")
        }
        assertTrue(
            image.colorModel.hasAlpha() && image.colorModel.numComponents == 4,
            "indexed PNG must decode to a 4-component ARGB ColorModel; " +
                    "got hasAlpha=${image.colorModel.hasAlpha()} " +
                    "numComponents=${image.colorModel.numComponents}"
        )
    }

    @Test
    fun rgbaPngDecodesAndNormalizesToArgb()
    {
        assertDecodesToArgb("rgba-32x32.png")
    }

    @Test
    fun gifDecodesAndNormalizesToArgb()
    {
        // GIF: JDK decodes to TYPE_BYTE_INDEXED (palette lookup).
        // Same ARGB-normalization path as indexed PNG.
        assertDecodesToArgb("rgb-32x32.gif")
    }

    @Test
    fun tiffDecodesThroughTwelveMonkeysAndNormalizesToArgb()
    {
        // TIFF baseline: JDK CAN handle, but TIFF variants (12-bit,
        // LZW, JPEG-in-TIFF) break the JDK reader. TwelveMonkeys
        // handles all of them. The fixture here is the simple case;
        // the regression the operator cares about is "any TIFF works
        // regardless of compression variant".
        assertDecodesToArgb("rgb-32x32.tiff")
    }

    @Test
    fun bmpDecodesAndNormalizesToArgb()
    {
        assertDecodesToArgb("rgb-32x32.bmp")
    }

    @Test
    fun unknownBytesRejectWithDescriptiveReason()
    {
        val garbage = ByteArray(200) { idx -> ((idx * 31) and 0xff).toByte() }
        val caught = try
        {
            ImageDecoder.decode(garbage)
            false
        }
        catch (e: ImageDecodeException)
        {
            assertTrue(
                e.message!!.contains("Unrecognized image format"),
                "rejection message must identify the failure mode. Got: ${e.message}"
            )
            true
        }
        assertTrue(caught, "decoder must throw ImageDecodeException for unrecognized bytes")
    }

    @Test
    fun emptyBytesRejectWithDescriptiveReason()
    {
        val caught = try
        {
            ImageDecoder.decode(ByteArray(0))
            false
        }
        catch (e: IllegalArgumentException)
        {
            assertTrue(
                e.message!!.contains("empty"),
                "empty-bytes rejection must mention 'empty'. Got: ${e.message}"
            )
            true
        }
        assertTrue(caught, "decoder must reject empty bytes")
    }

    /**
     * End-to-end contract: an oversized image that triggers the
     * iterated-halving downsample MUST produce a PNG under the
     * 408 KB ceiling regardless of source format. Exercises the
     * decoder + downsample loop together for an indexed PNG and a
     * CMYK JPEG — the two formats that previously failed before the
     * loop even started.
     */
    @Test
    fun oversizedIndexedPngDownsamplesUnderCap()
    {
        // Build an oversized indexed PNG in-memory rather than shipping
        // a 14 MB fixture. The contract we care about is: "an image
        // bigger than the cap, in a format the old decoder choked on,
        // now produces a PNG under the cap."
        val oversized = makeOversizedIndexedPng(2048, 2048)
        assertTrue(oversized.size > 408_000, "fixture sanity: oversized indexed PNG must exceed cap")

        val downsampled = downsampleForTest(oversized)
        assertTrue(
            downsampled.size <= 408_293,
            "downsample of oversized indexed PNG must produce <=408 KB output. " +
                    "Got ${downsampled.size} bytes. This is the Sand Martello failure mode: " +
                    "before the fix, the original oversized bytes were passed unchanged to " +
                    "the safety classifier."
        )
    }

    private fun makeOversizedIndexedPng(width: Int, height: Int): ByteArray
    {
        // Use the JDK to encode (the encoder is fine; only the decoder chokes on indexed).
        // TYPE_BYTE_INDEXED = 13 per BufferedImage Javadoc.
        val indexed = BufferedImage(width, height, 13)
        val g = indexed.createGraphics()
        try
        {
            // Fill with random colors so the PNG can't deflate-compress below cap.
            val random = java.util.Random(42)
            for (i in 0 until (width * height))
            {
                val x = i % width
                val y = i / width
                indexed.setRGB(x, y, random.nextInt())
            }
        }
        finally
        {
            g.dispose()
        }
        val out = java.io.ByteArrayOutputStream()
        ImageIO.write(indexed, "png", out)
        return out.toByteArray()
    }

    private fun downsampleForTest(bytes: ByteArray): ByteArray
    {
        // Mirror MapPackManager.downsampleImageBytesForPack inline so
        // the test exercises the same algorithm without depending on
        // the packer zip-out step. Uses the same TYPE_INT_ARGB
        // destination pattern the production code uses.
        val capBytes = (256_000 / 0.627).toInt()
        val maxDim = 1024
        val minDim = 64
        val src = ImageDecoder.decode(bytes)
        var currentMaxDim = maxDim
        var lastEncoded = bytes
        while (currentMaxDim >= minDim)
        {
            val longestEdge = maxOf(src.width, src.height)
            if (longestEdge <= currentMaxDim) return bytes
            val scale = currentMaxDim.toDouble() / longestEdge
            val dstW = (src.width * scale).toInt().coerceAtLeast(1)
            val dstH = (src.height * scale).toInt().coerceAtLeast(1)
            val dst = BufferedImage(dstW, dstH, BufferedImage_TYPE_INT_ARGB)
            val g2 = dst.createGraphics()
            try
            {
                g2.drawImage(src, 0, 0, dstW, dstH, null)
            }
            finally
            {
                g2.dispose()
            }
            val out = java.io.ByteArrayOutputStream()
            ImageIO.write(dst, "png", out)
            val encoded = out.toByteArray()
            lastEncoded = encoded
            if (encoded.size <= capBytes) return encoded
            currentMaxDim /= 2
        }
        return lastEncoded
    }

    companion object
    {
        // TYPE_INT_ARGB on this JVM — used by the downsample helper.
        // (The BufferedImage constructor accepts both constants; the
        // JDK quirk where the resulting `type` field is normalized to
        // TYPE_INT_RGB doesn't affect construction.)
        private const val BufferedImage_TYPE_INT_ARGB = 6
    }
}