package org.ttt.autogenesis.server.push

import org.bouncycastle.jce.provider.BouncyCastleProvider
import org.ttt.autogenesis.logging.LogCategory
import org.ttt.autogenesis.logging.Logger
import java.io.File
import java.security.KeyFactory
import java.security.PrivateKey
import java.security.Security
import java.security.spec.PKCS8EncodedKeySpec
import java.util.Base64

/**
 * Loads the VAPID P-256 ECDSA keypair from disk for Web Push authentication.
 *
 * The PEM private key file is generated by the `generateVapidKeys` Gradle task
 * in `kvisionApp/build.gradle.kts` if it does not already exist. The
 * `nl.martijndwars:web-push` library expects BOTH the public and private keys
 * as Base64URL-encoded strings (not as Java `Key` objects), so this loader
 * also extracts the public key and exposes it in the same encoding the
 * browser uses for `applicationServerKey`.
 *
 * Override the private key path with the `AUTOGENESIS_VAPID_PRIVATE_KEY`
 * environment variable.
 */
object PushVapidConfig
{
    private const val DEFAULT_KEY_PATH_SUFFIX = "/.autogenesis/vapid_private.pem"
    private const val CONTACT = "mailto:admin@autogenesis.example.com"
    private const val ENV_OVERRIDE = "AUTOGENESIS_VAPID_PRIVATE_KEY"

    init
    {
        // nl.martijndwars.webpush.Utils.loadPublicKey hard-codes the BC
        // provider name and throws NoSuchProviderException otherwise.
        // bcprov-jdk18on is on the runtime classpath via server/build.gradle.kts;
        // we only need to register it once at class-load time. Idempotent —
        // addProvider is a no-op for an already-registered name.
        if (Security.getProvider(BouncyCastleProvider.PROVIDER_NAME) == null)
        {
            Security.addProvider(BouncyCastleProvider())
        }
    }

    /**
     * Holds the VAPID keypair in the encoding the web-push library wants.
     * `publicKeyBase64Url` is the raw uncompressed EC point (65 bytes) encoded
     * without padding (this matches the encoding browsers expect for
     * `applicationServerKey` in `pushManager.subscribe()`).
     * `privateKeyBase64Url` is the PKCS8-encoded private key in Base64URL.
     */
    data class VapidKeypair(
        val publicKeyBase64Url: String,
        val privateKeyBase64Url: String,
        val privateKey: PrivateKey,
    )
    {
        /**
         * Reconstructs a Java `PublicKey` from the Base64URL-encoded raw
         * uncompressed point using `nl.martijndwars.webpush.Utils.loadPublicKey`,
         * which is the library's own helper. This avoids having to wire up
         * Bouncy Castle's ECNamedCurveParameterSpec / ECPublicKeySpec pair
         * ourselves.
         */
        fun publicKeyAsPublicKey(): java.security.PublicKey
        {
            return nl.martijndwars.webpush.Utils.loadPublicKey(publicKeyBase64Url)
        }
    }

    fun resolvePrivateKeyPath(): String
    {
        val fromEnv = System.getenv(ENV_OVERRIDE)
        if (!fromEnv.isNullOrBlank()) return fromEnv
        val home = System.getProperty("user.home")
            ?: System.getenv("HOME")
            ?: error("Cannot resolve user home for VAPID private key path")
        return home + DEFAULT_KEY_PATH_SUFFIX
    }

    /**
     * Loads the VAPID keypair. Returns null if the PEM file is missing,
     * unparseable, or the public-key extraction fails — callers should treat
     * null as "push disabled" and log appropriately. Never throws.
     */
    fun loadKeypair(): VapidKeypair?
    {
        val path = resolvePrivateKeyPath()
        val pemFile = File(path)
        if (!pemFile.exists())
        {
            Logger.warn(LogCategory.SYSTEM, "PushVapidConfig: VAPID private key not found at $path — push notifications disabled (run :kvisionApp:generateVapidKeys to create)")
            return null
        }
        return try
        {
            // The PEM generated by `openssl ecparam -name prime256v1 -genkey
            // -noout` is SEC1 ("BEGIN EC PRIVATE KEY") and Java's KeyFactory
            // rejects it when passed PKCS8EncodedKeySpec. Pipe through openssl
            // pkcs8 to canonicalize before parsing — same approach the JVM
            // integration test uses (which constructs KeyPairGenerator directly
            // to sidestep the issue). BouncyCastle would do this in-process but
            // the bcpkix dep isn't on the runtime classpath; this stays
            // shell-only.
            val canonical = ProcessBuilder(
                "openssl", "pkcs8", "-topk8", "-nocrypt",
                "-in", pemFile.absolutePath
            ).redirectErrorStream(true).start()
            val canonicalOut = canonical.inputStream.readBytes()
            check(canonical.waitFor() == 0) {
                "openssl pkcs8 normalization failed: ${String(canonicalOut)}"
            }
            val canonicalPem = String(canonicalOut)
                .replace("-----BEGIN PRIVATE KEY-----", "")
                .replace("-----END PRIVATE KEY-----", "")
                .replace("\\s+".toRegex(), "")
            val der = Base64.getDecoder().decode(canonicalPem)
            val keyFactory = KeyFactory.getInstance("EC")
            val privateKey = keyFactory.generatePrivate(PKCS8EncodedKeySpec(der))
            val privateKeyBase64Url = Base64.getUrlEncoder().withoutPadding().encodeToString(der)
            // Extract public key as DER (SubjectPublicKeyInfo), strip the last
            // 65 bytes (the raw uncompressed P-256 point 0x04 || X || Y).
            val derProcess = ProcessBuilder(
                "openssl", "ec", "-in", pemFile.absolutePath, "-pubout",
                "-outform", "DER"
            ).redirectErrorStream(true).start()
            val derBytes = derProcess.inputStream.readBytes()
            check(derProcess.waitFor() == 0) { "openssl ec -pubout failed: ${String(derBytes)}" }
            val rawPoint = derBytes.copyOfRange(derBytes.size - 65, derBytes.size)
            val publicKeyBase64Url = Base64.getUrlEncoder().withoutPadding().encodeToString(rawPoint)
            VapidKeypair(publicKeyBase64Url, privateKeyBase64Url, privateKey)
        }
        catch (e: Throwable)
        {
            Logger.error(LogCategory.SYSTEM, "PushVapidConfig: failed to load VAPID keypair at $path: ${e.message}")
            null
        }
    }

    fun getContact(): String = CONTACT
}
