import { chromium } from 'playwright';
import { writeFileSync } from 'fs';

const browser = await chromium.launch({ headless: true, args: ['--no-sandbox'] });
const ctx = await browser.newContext({ viewport: { width: 1280, height: 800 } });
const page = await ctx.newPage();
const captured = [];
page.on('console', msg => captured.push(`[${msg.type()}] ${msg.text()}`));
await page.goto('http://localhost:8080/?skipLogin=true', { waitUntil: 'load' });
await page.waitForTimeout(30000);
await ctx.close();
await browser.close();
const all = captured.join('\n');
console.log('total:', captured.length);
console.log('all length:', all.length);
writeFileSync('/tmp/quick-test-output.txt', all);
console.log('written to /tmp/quick-test-output.txt');
const re = /RpcRegistrationCollector:\s*Registering provider\s+MapUploadSuccessClientHandlersRegistrationProvider/i;
const m = all.match(re);
console.log('match found:', !!m);
if (m) console.log('match[0]:', m[0]);
const idx = all.indexOf('MapUploadSuccessClientHandlersRegistrationProvider');
console.log('substring index:', idx);
if (idx >= 0) console.log('context:', all.slice(Math.max(0, idx - 80), idx + 100));
console.log('---');
console.log('all.length:', all.length);
console.log('captured.length:', captured.length);
const lineFor = captured.find(c => c.includes('Registering provider UiSignal'));
if (lineFor) console.log('first Registering line:', lineFor);
